### ISSUE TITLE
Test case & documentation?

### ISSUE THREAD

**Issue by brody2consult** [oliversalzburg/is-junction#1]
Would be handy

P.S. Will you publish this one?

**Comment by oliversalzburg** [comment]
Yeah, I'll work on it a little more. I'm still hoping the module won't be necessary at all.

**Comment by oliversalzburg** [comment]
Added tests and an approach to handle calls on non-Windows OS. Documentation still pending.

**Comment by brody2consult** [comment]
Nice. My theory is that you never know when someone else will need your work, someday:)

**Comment by oliversalzburg** [comment]
Looks good enough for me now. :)

I'll publish this if no other solution comes up. Still trying to get some feedback from NodeJS developers. A friend indicated to me that this might need to be resolved in libuv. We'll see.

**Comment by brody2consult** [comment]
> A friend indicated to me that this might need to be resolved in libuv.

Support in libuv would be really nice. Should we start another discussion there?

**Comment by oliversalzburg** [comment]
It would really be nice to get some feedback from someone with more Node knowledge. I have little understanding of libuv and there still is no definite "it's not possible" yet.
